### ISSUE TITLE
A: Camera controls

### ISSUE THREAD

**Issue by frettingweasel** [frettingweasel/scene-is-believing#1]
LEFT MOUSE:    LEFT/RIGHT  -> rotate around axis perp. to ground (y axis)
LEFT MOUSE:    UP/DOWN     -> zoom

MID  MOUSE:     LEFT/RIGHT  -> same as left mouse left/right
MID MOUSE:      UP/DOWN     -> angle of elevation looking at origin (tilts scene)

**Comment by tmennell** [comment]
Implemented in merge #10
