### ISSUE TITLE
B: Object control - rotation

### ISSUE THREAD

**Issue by frettingweasel** [frettingweasel/scene-is-believing#2]
LEFT MOUSE: LEFT/RIGHT -> rotate current object about y axis
LEFT MOUSE: UP/DOWN    -> rotate current object about x axis

MID MOUSE: LEFT/RIGHT -> rotate current object about z axis
MID MOUSE: UP/DOWN    -> change current object texture scale

**Comment by tmennell** [comment]
Done #12.
