### ISSUE TITLE
E: Reshape function

### ISSUE THREAD

**Issue by frettingweasel** [frettingweasel/scene-is-believing#5]
Need to zoom out when the window is made smaller and zoom in when  window is made bigger.

If there is an object at the origin, it is kept in the window during resizes.

This already works for vertical resizes.  Need to implement for horizontal resizes.

**Comment by frettingweasel** [comment]
* Viewport fully populates the reshaped window.  It is never stretched or shrunk.
* The scale of the viewport relative to the window is determined by the size of the largest square that can fit into the window, ie. if the window is made wider than it is tall without manipulating the height of the window, the scale will remain unchanged and the viewport will show more of the scene (horizontally).  Likewise, if the window is made taller than it is wide without manipulating the width of the window, the scale will remain unchanged and the viewport will show more of the scene (vertically).  If the window is reshaped in a way that both the height and width are increased or decreased, then the viewport will scale accordingly.

**Comment by tmennell** [comment]
Reshaping as required
